### ISSUE TITLE
Fails during AoT compilation

### ISSUE THREAD

**Issue by alex-steel** [doorgets/ng-translate#1]
AoT compilation with ngc produces the following error:

Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule

The issue is most likely connected with not providing index.metadata.json file in the library.
angular/angular#11262 (comment)
angular/angular#11262 (comment)

**Comment by mounirrquiba** [comment]
Thanks Alex Steel 👍
